//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inteview_task.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public string Item_name { get; set; }
        public Nullable<int> Quntity { get; set; }
        public Nullable<int> Unit_price { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
